"""
backend/routes/dashboard_routes.py
==================================
Routes for primary page rendering, CSV dataset ingestion, and text report downloads.
"""

import os
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, send_file, session, current_app
from services.dashboard_service import get_cached_data, ensure_session_data
from utils.file_handler import save_uploaded_file
from utils.logger import logger

dashboard_bp = Blueprint("dashboard", __name__)

@dashboard_bp.route("/")
def index():
    """
    Renders the main ingestion gateway HTML page.
    """
    logger.info("Accessing Dataset Ingestion Gateway.")
    return render_template("index.html", show_dashboard=False)


@dashboard_bp.route("/upload", methods=["POST"])
def upload():
    """
    Handles CSV upload (or defaults to the sample dataset if no file is chosen).
    """
    logger.info("File upload request received.")
    filepath = None
    
    upload_dir = current_app.config["UPLOAD_DIR"]
    data_dir = current_app.config["DATA_DIR"]
    allowed_ext = current_app.config["ALLOWED_EXTENSIONS"]
    
    if "file" in request.files and request.files["file"].filename != "":
        try:
            filepath = save_uploaded_file(request.files["file"], upload_dir, allowed_ext)
            logger.info(f"Custom dataset uploaded successfully: {filepath}")
        except Exception as err:
            logger.error(f"Upload blocked or failed: {err}")
            return jsonify({"error": str(err)}), 400
    else:
        # Fallback to default baseline dataset
        filepath = os.path.join(data_dir, "crime_dataset_india.csv")
        if not os.path.exists(filepath):
            logger.error(f"Sample dataset file missing at: {filepath}")
            return jsonify({"error": "No dataset found. Please upload a CSV file."}), 400
        logger.info("Session using baseline Indian sample dataset.")
        
    try:
        get_cached_data(filepath)
        session["dataset_path"] = filepath
    except Exception as e:
        logger.error(f"Failed to read CSV: {e}", exc_info=True)
        return jsonify({"error": f"Failed to read CSV: {e}"}), 400
        
    return redirect(url_for("dashboard.dashboard"))


@dashboard_bp.route("/dashboard")
def dashboard():
    """
    Renders the Command Center dashboard page loaded with pre-warmed cache parameters.
    """
    data_dir = current_app.config["DATA_DIR"]
    if not ensure_session_data(data_dir):
        logger.warning("No active session dataset found. Redirecting to gateway.")
        return redirect(url_for("dashboard.index"))
        
    cache = get_cached_data(session["dataset_path"])
    return render_template(
        "dashboard.html",
        summary=cache["summary"],
        ml=cache["ml"],
        row_count=len(cache["df"]),
        show_dashboard=True,
    )


@dashboard_bp.route("/download")
def download():
    """
    Generates a plaintext forensic analysis report and streams it as a download.
    """
    data_dir = current_app.config["DATA_DIR"]
    graphs_dir = current_app.config["GRAPHS_DIR"]
    
    if not ensure_session_data(data_dir):
        logger.warning("Download aborted: No dataset loaded in session.")
        return redirect(url_for("dashboard.index"))
        
    cache = get_cached_data(session["dataset_path"])
    s = cache["summary"]
    ml_data = cache["ml"]
    
    preds = ml_data.get("predictions", {})
    pred_lines = "\n".join(f"  {yr}: {cnt} cases" for yr, cnt in preds.items())
    
    report = f"""
CRIME DATA ANALYSIS REPORT
===========================
Generated by AI-Powered Crime Data Analysis System

DATASET SUMMARY
---------------
Total Cases     : {s['total_cases']:,}
Closed Cases    : {s['closed_cases']:,}
Open Cases      : {s['open_cases']:,}
Closure Rate    : {s['closure_rate']}
Top Crime City  : {s['top_city']}
Most Used Weapon: {s['top_weapon']}

ML PREDICTION (Linear Regression)
-----------------------------------
Model R² Score  : {ml_data.get('r2_score', 'N/A')}
Forecasted Crime Counts:
{pred_lines}

CHARTS GENERATED
----------------
1. Bar Chart   – Top 10 Cities by Crime Count
2. Pie Chart   – Crime Domain Distribution
3. Heatmap     – Monthly Crime Frequency by City
4. Line Chart  – Crime Evolution Timeline
5. Scatter Plot– Victim Age vs Police Deployed
6. Prediction  – Future Crime Trend (ML)

===========================
End of Report
""".strip()

    os.makedirs(graphs_dir, exist_ok=True)
    report_path = os.path.join(graphs_dir, "crime_report.txt")
    
    logger.info(f"Generating plaintext download report at: {report_path}")
    with open(report_path, "w", encoding="utf-8") as fh:
        fh.write(report)
        
    return send_file(
        report_path, 
        as_attachment=True,
        download_name="crime_analysis_report.txt"
    )
